-- DOCUMENT_AUDIT
DELETE FROM DOCUMENT_AUDIT;

INSERT INTO DOCUMENT_AUDIT (ID_DOC, ID_VER, NM_DOC, ID_DOC_TYPE, ID_DOC_REPO, DOC_HYPERLINK, DOC_LOCATION, IS_DELETED, IS_VALID_LINK, CREATED_BY, CREATION_DT, LAST_UPDATED_BY, LAST_UPDATE_DT) VALUES ('1', '1', 'W2 Form', '3', '1', 'http://sharepoint.cognizant.com', '/apps/doc/tax', 'N', 'Y', 'PRATIK', '2015/07/03', null, null);
INSERT INTO DOCUMENT_AUDIT (ID_DOC, ID_VER, NM_DOC, ID_DOC_TYPE, ID_DOC_REPO, DOC_HYPERLINK, DOC_LOCATION, IS_DELETED, IS_VALID_LINK, CREATED_BY, CREATION_DT, LAST_UPDATED_BY, LAST_UPDATE_DT) VALUES ('2', '1', 'K1 Form', '2', '2', 'https://citadel.com', '/apps/doc/legal', 'N', 'Y', 'ARDHENDU', '2015/07/03', null, null);
INSERT INTO DOCUMENT_AUDIT (ID_DOC, ID_VER, NM_DOC, ID_DOC_TYPE, ID_DOC_REPO, DOC_HYPERLINK, DOC_LOCATION, IS_DELETED, IS_VALID_LINK, CREATED_BY, CREATION_DT, LAST_UPDATED_BY, LAST_UPDATE_DT) VALUES ('3', '1', 'IRA', '1', '3', 'https://www.livelink.com', '/apps/docs/ira', 'N', 'Y', 'PRATIK', '2015/07/03', null, null);


