-- DOC_TYPE
INSERT INTO DOC_TYPE (ID_DOC_TYPE, TX_DOC_TYPE) VALUES ('1', 'Trading Agreements');
INSERT INTO DOC_TYPE (ID_DOC_TYPE, TX_DOC_TYPE) VALUES ('2', 'Institutional');
INSERT INTO DOC_TYPE (ID_DOC_TYPE, TX_DOC_TYPE) VALUES ('3', 'Funds');
INSERT INTO DOC_TYPE (ID_DOC_TYPE, TX_DOC_TYPE) VALUES ('4', 'Intermediaries');
INSERT INTO DOC_TYPE (ID_DOC_TYPE, TX_DOC_TYPE) VALUES ('5', '');


