-- WF_GRP_ACTIVITY_MAP
DELETE FROM WF_GRP_ACTIVITY_MAP;

INSERT INTO WF_GRP_ACTIVITY_MAP (ID_WF_GRP, ID_WF_STATUS, TX_ACTIVITY_DESC) VALUES ('1', '1', 'Doc in New Status');
INSERT INTO WF_GRP_ACTIVITY_MAP (ID_WF_GRP, ID_WF_STATUS, TX_ACTIVITY_DESC) VALUES ('1', '2', 'Document Assigned to Maker - Business Mandated');
INSERT INTO WF_GRP_ACTIVITY_MAP (ID_WF_GRP, ID_WF_STATUS, TX_ACTIVITY_DESC) VALUES ('2', '3', 'Document in Maker - Fed Mandated Queue');
INSERT INTO WF_GRP_ACTIVITY_MAP (ID_WF_GRP, ID_WF_STATUS, TX_ACTIVITY_DESC) VALUES ('2', '4', 'Document assigned to Maker - Fed Mandated');
INSERT INTO WF_GRP_ACTIVITY_MAP (ID_WF_GRP, ID_WF_STATUS, TX_ACTIVITY_DESC) VALUES ('3', '5', 'Document in QA Queue');
INSERT INTO WF_GRP_ACTIVITY_MAP (ID_WF_GRP, ID_WF_STATUS, TX_ACTIVITY_DESC) VALUES ('3', '6', 'Document assigned to QA');
INSERT INTO WF_GRP_ACTIVITY_MAP (ID_WF_GRP, ID_WF_STATUS, TX_ACTIVITY_DESC) VALUES ('1', '7', 'Document assigned to Maker - Business Mandated to Complete');
INSERT INTO WF_GRP_ACTIVITY_MAP (ID_WF_GRP, ID_WF_STATUS, TX_ACTIVITY_DESC) VALUES ('1', '8', 'Document Marked Complete');


