-- DOC_TAG_REL
INSERT INTO DOC_TAG_REL (ID_DOC, ID_DOC_TYPE, ID_DOC_TAG, ID_DOC_SUB_TAG, CREATED_BY, CREATION_DT, LAST_UPDATED_BY, LAST_UPDATE_DT) VALUES ('1', '2', '3', '1', 'PRATIK', '2015/07/03', null, null);
INSERT INTO DOC_TAG_REL (ID_DOC, ID_DOC_TYPE, ID_DOC_TAG, ID_DOC_SUB_TAG, CREATED_BY, CREATION_DT, LAST_UPDATED_BY, LAST_UPDATE_DT) VALUES ('2', '1', '3', '2', 'ARDHENDU', '2015/07/03', null, null);
INSERT INTO DOC_TAG_REL (ID_DOC, ID_DOC_TYPE, ID_DOC_TAG, ID_DOC_SUB_TAG, CREATED_BY, CREATION_DT, LAST_UPDATED_BY, LAST_UPDATE_DT) VALUES ('3', '3', '1', '3', 'PRATIK', '2015/07/03', null, null);


