-- DOC_SUB_TAG_INFO
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('1', 'Governing Law1');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('2', 'Governing Law 2');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('3', 'Party Agreement 1');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('4', 'Party Agreement 2');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('5', 'Cross Default 1');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('6', '');


