-- DOC_WF_STATUS
DELETE FROM DOC_WF_STATUS;

INSERT INTO DOC_WF_STATUS (ID_WF_STATUS, NM_WF_STATUS, TX_WF_STATUS) VALUES ('1', 'New', 'New');
INSERT INTO DOC_WF_STATUS (ID_WF_STATUS, NM_WF_STATUS, TX_WF_STATUS) VALUES ('2', 'AN_ASG', 'Assigned to Analyst');
INSERT INTO DOC_WF_STATUS (ID_WF_STATUS, NM_WF_STATUS, TX_WF_STATUS) VALUES ('3', 'AN_RV', 'Analyst Reviewed');
INSERT INTO DOC_WF_STATUS (ID_WF_STATUS, NM_WF_STATUS, TX_WF_STATUS) VALUES ('4', 'AT_ASG', 'Assigned to Attorney');
INSERT INTO DOC_WF_STATUS (ID_WF_STATUS, NM_WF_STATUS, TX_WF_STATUS) VALUES ('5', 'AT_RV', 'Attorney Reviewed');
INSERT INTO DOC_WF_STATUS (ID_WF_STATUS, NM_WF_STATUS, TX_WF_STATUS) VALUES ('6', 'QA_ASG', 'Assigned to QA');
INSERT INTO DOC_WF_STATUS (ID_WF_STATUS, NM_WF_STATUS, TX_WF_STATUS) VALUES ('7', 'QA_RV', 'QA Reviewed');
INSERT INTO DOC_WF_STATUS (ID_WF_STATUS, NM_WF_STATUS, TX_WF_STATUS) VALUES ('8', 'CLOSE', 'Completed');


