-- DOC_TAG_INFO
INSERT INTO DOC_TAG_INFO (ID_DOC_TAG, TX_DOC_TAG) VALUES ('1', 'ISDA');
INSERT INTO DOC_TAG_INFO (ID_DOC_TAG, TX_DOC_TAG) VALUES ('2', 'Futures & Options');
INSERT INTO DOC_TAG_INFO (ID_DOC_TAG, TX_DOC_TAG) VALUES ('3', 'Investment Management Agreement');
INSERT INTO DOC_TAG_INFO (ID_DOC_TAG, TX_DOC_TAG) VALUES ('4', 'Supplemental Letters');
INSERT INTO DOC_TAG_INFO (ID_DOC_TAG, TX_DOC_TAG) VALUES ('5', 'Advisory Agreement');
INSERT INTO DOC_TAG_INFO (ID_DOC_TAG, TX_DOC_TAG) VALUES ('6', 'Sub-Advisory Agreement');
INSERT INTO DOC_TAG_INFO (ID_DOC_TAG, TX_DOC_TAG) VALUES ('7', 'Placement Agreement');


