-- DOC_WF_GRP
DELETE FROM DOC_WF_GRP;

INSERT INTO DOC_WF_GRP (ID_WF_GRP, NM_WF_GRP) VALUES ('1', 'Maker - Business Mandated');
INSERT INTO DOC_WF_GRP (ID_WF_GRP, NM_WF_GRP) VALUES ('2', 'Maker - Fed Mandated');
INSERT INTO DOC_WF_GRP (ID_WF_GRP, NM_WF_GRP) VALUES ('3', 'QA');


