-- DOC_TYPE_TAG_MAPPING
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('1', '1');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('1', '2');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('2', '3');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('2', '4');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('3', '5');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('3', '6');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('4', '');


