-- DOC_WORKFLOW_PROCESS_AUDIT
INSERT INTO DOC_WORKFLOW_PROCESS_AUDIT (ID_DOC, ID_VER, ID_WF_STATUS, IS_REWORKED, ASSIGNED_TO, ASSIGNED_DT, ID_ROLE, LAST_UPDATED_BY, LAST_UPDATE_DT) VALUES ('1', '1', '1', 'N', '', '', '', '', '');
INSERT INTO DOC_WORKFLOW_PROCESS_AUDIT (ID_DOC, ID_VER, ID_WF_STATUS, IS_REWORKED, ASSIGNED_TO, ASSIGNED_DT, ID_ROLE, LAST_UPDATED_BY, LAST_UPDATE_DT) VALUES ('2', '1', '1', 'N', '', '', '', '', '');
INSERT INTO DOC_WORKFLOW_PROCESS_AUDIT (ID_DOC, ID_VER, ID_WF_STATUS, IS_REWORKED, ASSIGNED_TO, ASSIGNED_DT, ID_ROLE, LAST_UPDATED_BY, LAST_UPDATE_DT) VALUES ('3', '1', '1', 'N', '', '', '', '', '');


