-- DOC_WF_GRP
INSERT INTO DOC_WF_GRP (ID_WF_GRP, NM_WF_GRP) VALUES ('1', 'Analyst');
INSERT INTO DOC_WF_GRP (ID_WF_GRP, NM_WF_GRP) VALUES ('2', 'Attorney');
INSERT INTO DOC_WF_GRP (ID_WF_GRP, NM_WF_GRP) VALUES ('3', 'QA');


