-- WF_GRP_ACTIVITY_MAP
DELETE FROM WF_GRP_ACTIVITY_MAP;

INSERT INTO WF_GRP_ACTIVITY_MAP (ID_WF_GRP, ID_WF_STATUS, TX_ACTIVITY_DESC) VALUES ('1', '1', 'Doc in New Status');
INSERT INTO WF_GRP_ACTIVITY_MAP (ID_WF_GRP, ID_WF_STATUS, TX_ACTIVITY_DESC) VALUES ('1', '2', 'Document Assigned to Analyst');
INSERT INTO WF_GRP_ACTIVITY_MAP (ID_WF_GRP, ID_WF_STATUS, TX_ACTIVITY_DESC) VALUES ('2', '3', 'Document in Attorney Queue');
INSERT INTO WF_GRP_ACTIVITY_MAP (ID_WF_GRP, ID_WF_STATUS, TX_ACTIVITY_DESC) VALUES ('2', '4', 'Document assigned to Attorney');
INSERT INTO WF_GRP_ACTIVITY_MAP (ID_WF_GRP, ID_WF_STATUS, TX_ACTIVITY_DESC) VALUES ('3', '5', 'Document in Lead Attorney Queue');
INSERT INTO WF_GRP_ACTIVITY_MAP (ID_WF_GRP, ID_WF_STATUS, TX_ACTIVITY_DESC) VALUES ('3', '6', 'Document assigned to Lead Attorney');
INSERT INTO WF_GRP_ACTIVITY_MAP (ID_WF_GRP, ID_WF_STATUS, TX_ACTIVITY_DESC) VALUES ('1', '7', 'Document left for Analyst to Complete');


