-- DOC_TAG_SUBTAG_MAP
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('1', '3');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('1', '4');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('2', '5');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('3', '1');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('3', '2');


