-- DOC_REPO
INSERT INTO DOC_REPO (ID_DOC_REPO, TX_DOC_REPO) VALUES ('1', 'Sharepoint');
INSERT INTO DOC_REPO (ID_DOC_REPO, TX_DOC_REPO) VALUES ('2', 'Citadel');
INSERT INTO DOC_REPO (ID_DOC_REPO, TX_DOC_REPO) VALUES ('3', 'Livelink');


