\. D:\git\localdestination\model\db\INS_USER.sql
\. D:\git\localdestination\model\db\INS_ROLE.sql
\. D:\git\localdestination\model\db\INS_USER_ROLE_MAP.sql
\. D:\git\localdestination\model\db\INS_DOC_REPO.sql
\. D:\git\localdestination\model\db\INS_DOC_TYPE.sql
\. D:\git\localdestination\model\db\INS_DOC_TAG_INFO.sql
\. D:\git\localdestination\model\db\INS_DOC_TYPE_TAG_MAPPING.sql
\. D:\git\localdestination\model\db\INS_DOC_SUB_TAG_INFO.sql
\. D:\git\localdestination\model\db\INS_DOC_TAG_SUBTAG_MAP.sql
\. D:\git\localdestination\model\db\INS_DOCUMENT.sql
\. D:\git\localdestination\model\db\INS_DOCUMENT_AUDIT.sql
\. D:\git\localdestination\model\db\INS_DOC_TAG_REL.sql
\. D:\git\localdestination\model\db\INS_DOC_TAG_REL_AUDIT.sql
\. D:\git\localdestination\model\db\INS_DOC_WF_STATUS.sql
\. D:\git\localdestination\model\db\INS_WF_GRP.sql
\. D:\git\localdestination\model\db\INS_WF_GRP_ACTIVITY_MAP.sql
\. D:\git\localdestination\model\db\INS_DOC_WORKFLOW_PROCESS.sql
\. D:\git\localdestination\model\db\INS_DOC_WORKFLOW_PROCESS_AUDIT.sql