USE TEST;
DELETE FROM ROLE;

INSERT INTO ROLE (ID_ROLE, NM_ROLE, TX_ROLE) VALUES (1, 'Maker', 'Maker');
INSERT INTO ROLE (ID_ROLE, NM_ROLE, TX_ROLE) VALUES (2, 'Checker', 'Checker');
INSERT INTO ROLE (ID_ROLE, NM_ROLE, TX_ROLE) VALUES (3, 'Onshore SME', 'Onshore SME');
INSERT INTO ROLE (ID_ROLE, NM_ROLE, TX_ROLE) VALUES (4, 'System Admin', 'System Admin');


