USE TEST;
DELETE FROM ERR_REASON;

INSERT INTO ERR_REASON (ID_ERR_REASON, TX_ERR_REASON) VALUES (1,  'Governing Law');
INSERT INTO ERR_REASON (ID_ERR_REASON, TX_ERR_REASON) VALUES (2,  'Material Adverse');
INSERT INTO ERR_REASON (ID_ERR_REASON, TX_ERR_REASON) VALUES (3,  'Party Name');
INSERT INTO ERR_REASON (ID_ERR_REASON, TX_ERR_REASON) VALUES (4,  'Termination');
