USE TEST;
-- ROLE_STATUS_MAPPING
DELETE FROM ROLE_STATUS_MAPPING;

/*INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (1, 1);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (1, 2);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (1, 3);*/
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (1, 4);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (1, 5);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (1, 6);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (1, 7);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (1, 8);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (1, 9);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (1, 10);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (1, 11);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (1, 12);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (1, 13);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (1, 14);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (1, 15);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (2, 4);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (2, 5);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (2, 6);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (2, 7);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (2, 8);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (2, 9);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (2, 10);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (2, 11);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (2, 12);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (2, 13);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (2, 14);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (2, 15);
/*INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (2, 16);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (2, 17);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (2, 18);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (3, 19);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (3, 20);*/
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (3, 21);
-- INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (3, 22);
INSERT INTO ROLE_STATUS_MAPPING (ID_ROLE, ID_WF_STATUS) VALUES (4, -1); /* Access to everything*/