USE TEST;
-- USER_ROLE_MAP
DELETE FROM USER_ROLE_MAP;

/*INSERT INTO USER_ROLE_MAP (ID_USER, ID_ROLE, CREATED_BY, CREATION_DT, UPDATED_BY, UPDATE_DT) VALUES ('ARDHENDU', 1, 'PRATIK', '2015/07/03', 'PRATIK', '2015/07/03');
INSERT INTO USER_ROLE_MAP (ID_USER, ID_ROLE, CREATED_BY, CREATION_DT, UPDATED_BY, UPDATE_DT) VALUES ('PRATIK', 1, 'PRATIK', '2015/07/03', 'PRATIK', '2015/07/03');
INSERT INTO USER_ROLE_MAP (ID_USER, ID_ROLE, CREATED_BY, CREATION_DT, UPDATED_BY, UPDATE_DT) VALUES ('BIDIT', 2, 'PRATIK', '2015/07/03', 'PRATIK', '2015/07/03');
INSERT INTO USER_ROLE_MAP (ID_USER, ID_ROLE, CREATED_BY, CREATION_DT, UPDATED_BY, UPDATE_DT) VALUES ('RASHMI', 2, 'PRATIK', '2015/07/03', 'PRATIK', '2015/07/03');
INSERT INTO USER_ROLE_MAP (ID_USER, ID_ROLE, CREATED_BY, CREATION_DT, UPDATED_BY, UPDATE_DT) VALUES ('MRINAL', 3, 'PRATIK', '2015/07/03', 'PRATIK', '2015/07/03');
INSERT INTO USER_ROLE_MAP (ID_USER, ID_ROLE, CREATED_BY, CREATION_DT, UPDATED_BY, UPDATE_DT) VALUES ('DEBASISH', 4, 'PRATIK', '2015/07/09', 'PRATIK', '2015/07/09');*/
INSERT INTO USER_ROLE_MAP (ID_USER, ID_ROLE, CREATED_BY, CREATION_DT, UPDATED_BY, UPDATE_DT) VALUES ('ADMIN', 4, 'PRATIK', '2015/07/09', 'PRATIK', '2015/07/09');
/*INSERT INTO USER_ROLE_MAP (ID_USER, ID_ROLE, CREATED_BY, CREATION_DT, UPDATED_BY, UPDATE_DT) VALUES ('BIDIT', 2, 'PRATIK', '2015/07/03', 'PRATIK', '2015/07/03');
INSERT INTO USER_ROLE_MAP (ID_USER, ID_ROLE, CREATED_BY, CREATION_DT, UPDATED_BY, UPDATE_DT) VALUES ('SHUBHRAJIT', 3, 'PRATIK', '2015/07/03', 'PRATIK', '2015/07/03');
INSERT INTO USER_ROLE_MAP (ID_USER, ID_ROLE, CREATED_BY, CREATION_DT, UPDATED_BY, UPDATE_DT) VALUES ('SHUBHRAJIT', 4, 'PRATIK', '2015/07/09', 'PRATIK', '2015/07/09');*/