USE TEST;
-- USER
DELETE FROM USER;

/*INSERT INTO USER (ID_USER, NM_USER, PASSWORD, PASSWORD_TYPE, USER_STATUS, CREATED_BY, CREATION_DT, LAST_LOGIN, UPDATED_BY, UPDATE_DT) VALUES ('ARDHENDU', 'ARDHENDU PRASANNA MAJUMDAR', 'password', 'T', 'Active', 'PRATIK', '2015/07/03', '2015/07/03', 'PRATIK', '2015/07/03');
INSERT INTO USER (ID_USER, NM_USER, PASSWORD, PASSWORD_TYPE, USER_STATUS, CREATED_BY, CREATION_DT, LAST_LOGIN, UPDATED_BY, UPDATE_DT) VALUES ('PRATIK', 'PRATIK ROY', 'password', 'T', 'Active', 'PRATIK', '2015/07/03', '2015/07/03', 'PRATIK', '2015/07/03');
INSERT INTO USER (ID_USER, NM_USER, PASSWORD, PASSWORD_TYPE, USER_STATUS, CREATED_BY, CREATION_DT, LAST_LOGIN, UPDATED_BY, UPDATE_DT) VALUES ('MRINAL', 'MRINAL KANTI SAHA', 'password', 'T', 'Active', 'PRATIK', '2015/07/03', '2015/07/03', 'PRATIK', '2015/07/03');
INSERT INTO USER (ID_USER, NM_USER, PASSWORD, PASSWORD_TYPE, USER_STATUS, CREATED_BY, CREATION_DT, LAST_LOGIN, UPDATED_BY, UPDATE_DT) VALUES ('DEBASISH', 'DEBASISH NATH', 'password', 'T', 'Active', 'PRATIK', '2015/07/03', '2015/07/03', 'PRATIK', '2015/07/03');
INSERT INTO USER (ID_USER, NM_USER, PASSWORD, PASSWORD_TYPE, USER_STATUS, CREATED_BY, CREATION_DT, LAST_LOGIN, UPDATED_BY, UPDATE_DT) VALUES ('BIDIT', 'BIDIT PAKRASHI', 'password', 'T', 'Active', 'PRATIK', '2015/07/03', '2015/07/03', 'PRATIK', '2015/07/03');
INSERT INTO USER (ID_USER, NM_USER, PASSWORD, PASSWORD_TYPE, USER_STATUS, CREATED_BY, CREATION_DT, LAST_LOGIN, UPDATED_BY, UPDATE_DT) VALUES ('SHUBHRAJIT', 'SHUBHRAJIT CHATTERJEE', 'password', 'T', 'Active', 'PRATIK', '2015/07/03', '2015/07/03', 'PRATIK', '2015/07/03');
INSERT INTO USER (ID_USER, NM_USER, PASSWORD, PASSWORD_TYPE, USER_STATUS, CREATED_BY, CREATION_DT, LAST_LOGIN, UPDATED_BY, UPDATE_DT) VALUES ('RASHMI', 'RASHMI GHOSH', 'password', 'T', 'Active', 'PRATIK', '2015/07/03', '2015/07/03', 'PRATIK', '2015/07/03');*/
INSERT INTO USER (ID_USER, NM_USER, PASSWORD, PASSWORD_TYPE, USER_STATUS, CREATED_BY, CREATION_DT, LAST_LOGIN, UPDATED_BY, UPDATE_DT) VALUES ('ADMIN', 'ADMIN USER', 'password', 'T', 'Active', 'PRATIK', '2015/07/03', '2015/07/03', 'PRATIK', '2015/07/03');


