USE TEST;

DELETE FROM AGREEMENT_TYPE;

INSERT INTO AGREEMENT_TYPE (ID_AGREEMENT_TYPE,  TX_AGREEMENT_TYPE) VALUES (1, 'Trade Agreement');
INSERT INTO AGREEMENT_TYPE (ID_AGREEMENT_TYPE,  TX_AGREEMENT_TYPE) VALUES (2, 'ISDA Master');
INSERT INTO AGREEMENT_TYPE (ID_AGREEMENT_TYPE,  TX_AGREEMENT_TYPE) VALUES (3, 'IRS Document');


