\. D:\github\trunk\model\db2\DDL.sql
\. D:\github\trunk\model\db2\INS_AGREEMENT_TYPE.sql
\. D:\github\trunk\model\db2\INS_ERR_REASON.sql
\. D:\github\trunk\model\db2\INS_ROLE.sql
\. D:\github\trunk\model\db2\INS_WF_STATUS.sql
\. D:\github\trunk\model\db2\INS_USER.sql
\. D:\github\trunk\model\db2\INS_USER_ROLE_MAP.sql
\. D:\github\trunk\model\db2\INS_ROLE_STATUS_MAPPING.sql
\. D:\github\trunk\model\db2\AddAgreement.sql