/*
 * This source file was generated by the Gradle 'init' task
 */
package com.dbnath.cobol.parser;

import io.proleap.cobol.asg.metamodel.CompilationUnit;
import io.proleap.cobol.asg.metamodel.NamedElement;
import io.proleap.cobol.asg.metamodel.Program;
import io.proleap.cobol.asg.metamodel.ProgramUnit;
import io.proleap.cobol.asg.metamodel.call.Call;
import io.proleap.cobol.asg.metamodel.procedure.Paragraph;
import io.proleap.cobol.asg.metamodel.procedure.ProcedureDivision;
import io.proleap.cobol.asg.metamodel.procedure.Section;
import io.proleap.cobol.asg.metamodel.procedure.Statement;
import io.proleap.cobol.asg.metamodel.procedure.perform.PerformProcedureStatement;
import io.proleap.cobol.asg.metamodel.procedure.perform.PerformStatement;
import io.proleap.cobol.asg.params.CobolParserParams;
import io.proleap.cobol.asg.params.impl.CobolParserParamsImpl;
import io.proleap.cobol.asg.runner.impl.CobolParserRunnerImpl;
import io.proleap.cobol.preprocessor.CobolPreprocessor;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.ParserRuleContext;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.misc.Interval;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.*;
import java.util.stream.Collectors;

import static io.proleap.cobol.asg.metamodel.procedure.StatementTypeEnum.*;

public class App {

    public static void main(String[] args) throws Exception {

        java.io.File inputFile = new java.io.File("app/src/main/resources/data/CBACT01C.cbl");

        // generate ASG from plain COBOL code
        CobolParserParams cobolParserParams = new CobolParserParamsImpl();
        cobolParserParams.setFormat(CobolPreprocessor.CobolSourceFormatEnum.FIXED);
        cobolParserParams.setIgnoreSyntaxErrors(true);

        Program program = new CobolParserRunnerImpl().analyzeFile(inputFile,
                CobolPreprocessor.CobolSourceFormatEnum.FIXED);

        CompilationUnit compilationUnit = program.getCompilationUnit("CBACT01C");

        ProgramUnit programUnit = compilationUnit.getProgramUnit();

        // Extract Identification Division
        System.out.println("=== IDENTIFICATION DIVISION ===\n");
        System.out.println("Identification Name: " + programUnit.getIdentificationDivision()
                .getProgramIdParagraph().getName());

        // Extract Procedure Division
        ProcedureDivision procedureDivision = programUnit.getProcedureDivision();

        if (procedureDivision != null) {
            System.out.println("=== PROCEDURE DIVISION EXTRACTION ===\n");

            // Get all paragraphs (including those in sections)
            List<Paragraph> allParagraphs = procedureDivision.getParagraphs();
            System. out.println("Total Paragraphs: " + allParagraphs.size());

            // Get only root-level paragraphs (excluding those in sections)
            List<Paragraph> rootParagraphs = procedureDivision.getRootParagraphs();
            System. out.println("Root Paragraphs: " + rootParagraphs.size());

            // Get all sections
            List<Section> sections = procedureDivision.getSections();
            System. out. println("Total Sections: " + sections.size());

            // Get all statements directly in procedure division
            List<Statement> statements = procedureDivision.getStatements();
            System. out.println("Direct Statements: " + statements.size());

            // Extract all paragraphs and their logic
            extractParagraphs(procedureDivision);

            // Extract all sections and their logic
            extractSections(procedureDivision);
        }
    }

    private static void extractParagraphs(ProcedureDivision procedureDivision) {
        System.out.println("\n=== PARAGRAPHS ===");
        Map<String, List<String>> paragraphCalls = new HashMap<>();

        for (Paragraph paragraph: procedureDivision.getParagraphs()) {
            System.out.println("\nParagraph: " + paragraph.getName());

            // Get all statements in this paragraph
            List<Statement> statements = paragraph.getStatements();
            List<String> calledParagraphs = statements.stream()
                    .flatMap(stmt -> resolvePerformedParagraphs(stmt).stream())
                    .toList();
            paragraphCalls.put(paragraph.getName(), calledParagraphs);

            System. out.println("  Statements: " + statements.size());
            calledParagraphs.forEach(call -> System.out.println("    calls -> " + call));


            // Print each statement type
            for (Statement statement : statements) {
                String exact = sliceExactSource(statement.getCtx());
                System. out. println("    - " + exact);

                // You can extract specific statement details based on type
                switch (statement.getStatementType()) {
                    case DISPLAY:
                        // Handle DISPLAY statement
                        break;
                    case MOVE:
                        // Handle MOVE statement
                        break;
                    case PERFORM:
                        break;
                    case IF:
                        // Handle IF statement
                        break;
                    // Add more cases as needed
                    default:
                        break;
                }
            }
        }
    }

    private static void extractSections(ProcedureDivision procedureDivision) {
        System. out.println("\n=== SECTIONS ===");

        for (Section section: procedureDivision.getSections()) {
            System.out.println("\nSection: " + section.getName());

            // Get paragraphs within this section
            List<Paragraph> paragraphs = section.getParagraphs();
            System. out.println("  Paragraphs in section: " + paragraphs.size());

            for (Paragraph paragraph: paragraphs) {
                System. out. println("    Paragraph: " + paragraph.getName());

                List<Statement> statements = paragraph.getStatements();
                System.out.println("      Statements: " + statements.size());

                for (Statement statement: statements) {
                    System.out.println("        - " + sliceExactSource(statement.getCtx()));
                }
            }
        }
    }

    private static String sliceExactSource(ParserRuleContext ctx) {
        if (ctx == null) return "";
        Token start = ctx.getStart();
        Token stop = ctx.getStop();
        if (start == null || stop == null) return ctx.getText();
        CharStream input = start.getTokenSource().getInputStream();
        if (input == null) return ctx.getText();
        int startIdx = start.getStartIndex();
        int stopIdx = stop.getStopIndex();
        if (startIdx < 0 || stopIdx < startIdx) return ctx.getText();
        return input.getText(Interval.of(startIdx, stopIdx));
    }

    private static List<String> resolvePerformedParagraphs(Statement statement) {
        if (!statement.getCtx().getText().contains("PERFORM")) {
            return List.of();
        }
        List<String> calledParagraphs = new ArrayList<>();

        // Extract called paragraphs from PERFORM statements using regex
        String ctxText = sliceExactSource(statement.getCtx());
        String regex = "(?i)PERFORM\\s+([\\w-]+)";
        java.util.regex.Pattern pattern = java.util.regex.Pattern.compile(regex);
        java.util.regex.Matcher matcher = pattern.matcher(ctxText);
        while (matcher.find()) {
            calledParagraphs.add(matcher.group(1));
        }
        return calledParagraphs;
    }
}
