-- DOC_TAG_INFO

DELETE FROM DOC_TAG_INFO;

INSERT INTO DOC_TAG_INFO (ID_DOC_TAG, TX_DOC_TAG) VALUES ('1', 'Parties to the Agreement');
INSERT INTO DOC_TAG_INFO (ID_DOC_TAG, TX_DOC_TAG) VALUES ('2', 'Governing Law');
INSERT INTO DOC_TAG_INFO (ID_DOC_TAG, TX_DOC_TAG) VALUES ('3', 'Change in Control');
INSERT INTO DOC_TAG_INFO (ID_DOC_TAG, TX_DOC_TAG) VALUES ('4', 'Cross-Default');
INSERT INTO DOC_TAG_INFO (ID_DOC_TAG, TX_DOC_TAG) VALUES ('5', 'Events of Default');
INSERT INTO DOC_TAG_INFO (ID_DOC_TAG, TX_DOC_TAG) VALUES ('6', 'Term of the Agreement');
INSERT INTO DOC_TAG_INFO (ID_DOC_TAG, TX_DOC_TAG) VALUES ('7', 'Termination');
INSERT INTO DOC_TAG_INFO (ID_DOC_TAG, TX_DOC_TAG) VALUES ('8', 'Collateralization');
INSERT INTO DOC_TAG_INFO (ID_DOC_TAG, TX_DOC_TAG) VALUES ('9', 'Guarantees');
INSERT INTO DOC_TAG_INFO (ID_DOC_TAG, TX_DOC_TAG) VALUES ('10', 'Transferability');


