-- DOC_TAG_REL_AUDIT
DELETE FROM DOC_TAG_REL_AUDIT;

INSERT INTO DOC_TAG_REL_AUDIT (ID_DOC, ID_VER, ID_DOC_TYPE, ID_DOC_TAG, ID_DOC_SUB_TAG, CREATED_BY, CREATION_DT, LAST_UPDATED_BY, LAST_UPDATE_DT) VALUES ('1', '1', '2', '3', '1', 'PRATIK', '2015/07/03', '', '');
INSERT INTO DOC_TAG_REL_AUDIT (ID_DOC, ID_VER, ID_DOC_TYPE, ID_DOC_TAG, ID_DOC_SUB_TAG, CREATED_BY, CREATION_DT, LAST_UPDATED_BY, LAST_UPDATE_DT) VALUES ('2', '1', '1', '3', '2', 'ARDHENDU', '2015/07/03', '', '');
INSERT INTO DOC_TAG_REL_AUDIT (ID_DOC, ID_VER, ID_DOC_TYPE, ID_DOC_TAG, ID_DOC_SUB_TAG, CREATED_BY, CREATION_DT, LAST_UPDATED_BY, LAST_UPDATE_DT) VALUES ('3', '1', '3', '1', '3', 'PRATIK', '2015/07/03', '', '');


