-- DOC_WORKFLOW_PROCESS
DELETE FROM DOC_WORKFLOW_PROCESS;

INSERT INTO DOC_WORKFLOW_PROCESS (ID_DOC, ID_WF_STATUS, IS_REWORKED, ASSIGNED_TO, ASSIGNED_DT, ID_ROLE, LAST_UPDATED_BY, LAST_UPDATE_DT) VALUES ('1', '1', 'N', null, null, null, null, null);
INSERT INTO DOC_WORKFLOW_PROCESS (ID_DOC, ID_WF_STATUS, IS_REWORKED, ASSIGNED_TO, ASSIGNED_DT, ID_ROLE, LAST_UPDATED_BY, LAST_UPDATE_DT) VALUES ('2', '1', 'N', null, null, null, null, null);
INSERT INTO DOC_WORKFLOW_PROCESS (ID_DOC, ID_WF_STATUS, IS_REWORKED, ASSIGNED_TO, ASSIGNED_DT, ID_ROLE, LAST_UPDATED_BY, LAST_UPDATE_DT) VALUES ('3', '1', 'N', null, null, null, null, null);


