-- DOC_REPO
DELETE FROM DOC_REPO;
INSERT INTO DOC_REPO (ID_DOC_REPO, TX_DOC_REPO) VALUES ('1', 'Sharepoint');
INSERT INTO DOC_REPO (ID_DOC_REPO, TX_DOC_REPO) VALUES ('2', 'Citadel');
INSERT INTO DOC_REPO (ID_DOC_REPO, TX_DOC_REPO) VALUES ('3', 'Livelink');
INSERT INTO DOC_REPO (ID_DOC_REPO, TX_DOC_REPO) VALUES ('4', 'Windows K: Drive');
INSERT INTO DOC_REPO (ID_DOC_REPO, TX_DOC_REPO) VALUES ('5', 'Windows M: Drive');
INSERT INTO DOC_REPO (ID_DOC_REPO, TX_DOC_REPO) VALUES ('6', 'Windows D: Drive');
INSERT INTO DOC_REPO (ID_DOC_REPO, TX_DOC_REPO) VALUES ('7', 'Windows S: Drive');


