-- DOC_TYPE_TAG_MAPPING

DELETE FROM DOC_TYPE_TAG_MAPPING;

INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('1', '1');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('1', '2');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('1', '6');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('1', '7');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('1', '8');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('1', '9');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('2', '2');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('2', '3');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('2', '4');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('2', '5');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('3', '4');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('3', '6');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('3', '7');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('3', '8');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('3', '9');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('4', '5');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('4', '6');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('4', '7');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('4', '8');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('4', '9');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('4', '10');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('5', '1');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('5', '2');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('5', '3');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('5', '6');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('5', '8');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('5', '9');
INSERT INTO DOC_TYPE_TAG_MAPPING (ID_DOC_TYPE, ID_DOC_TAG) VALUES ('5', '10');


