-- DOC_SUB_TAG_INFO

DELETE FROM DOC_SUB_TAG_INFO;

INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('1', 'Governing Law1');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('2', 'Governing Law 2');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('3', 'Change in Control 1');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('4', 'Change in Control 2');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('5', 'Cross Default 1');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('6', 'Cross Default 2');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('7', 'Events of Default 1');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('8', 'Events of Default 2');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('9', 'Term of Agreement 1');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('10', 'Term of Agreement 2');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('11', 'Termination 1');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('12', 'Termination 2');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('13', 'Collateralization 1');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('14', 'Collateralization 2');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('15', 'Guarantees 1');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('16', 'Guarantees 2');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('17', 'Transferability 1');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('18', 'Transferability 2');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('19', 'Parties to the Agreement 1');
INSERT INTO DOC_SUB_TAG_INFO (ID_DOC_SUB_TAG, TX_DOC_SUB_TAG) VALUES ('20', 'Parties to the Agreement 2');


