-- DOC_TAG_SUBTAG_MAP

DELETE FROM DOC_TAG_SUBTAG_MAP;

INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('1', '19');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('1', '20');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('2', '1');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('2', '2');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('3', '3');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('3', '4');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('4', '5');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('4', '6');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('5', '7');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('5', '8');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('6', '9');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('6', '10');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('7', '11');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('7', '12');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('8', '13');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('8', '14');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('9', '15');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('9', '16');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('10', '17');
INSERT INTO DOC_TAG_SUBTAG_MAP (ID_DOC_TAG, ID_DOC_SUB_TAG) VALUES ('10', '18');


